sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 10
  - 12
  - 14
  - 16
script: npm run validate
jobs:
  include:
    - stage: release
      node_js: '14'
      deploy:
        provider: script
        script: npm run test:update && npx codecov && npx semantic-release
        skip_cleanup: true
branches:
  only: master
